---
# tasks file for awesome_mail

- name: Include vars.
  ansible.builtin.include_vars:
    dir: vars

- name: Send awesome stuff to your crew.
  community.general.mail:
    secure: "{{ mail_secure }}"
    port: "{{ mail_port }}"
    host: "{{ mail_host }}"
    to: "{{ mail_to }}"
    from: "{{ mail_from }}"
    subject: "{{ item.day }} {{ item.theme }}"
    body: "{{ item.quote }}"
  when: ansible_facts.date_time.weekday == item.day
  loop: "{{ random_quote }}"
  loop_control:
    label: "{{ item.day }} {{ item.quote }}"

- name: Schedule using cron.
  tags: [never, schedule]
  ansible.builtin.cron:
    name: Mail awesomeness
    job: cd {{ playbook_dir }} && ansible-playbook playbook_awesome_mail.yml
    hour: "{{ cron_hour }}"
    minute: "{{ cron_minute }}"
    state: present

- name: Print info about cron.
  tags: [never, schedule]
  ansible.builtin.debug:
    msg:
      - Use command 'crontab -l' to display the current crontab on standard output.
      - Use command 'crontab -r' to remove the current crontab.
